package src.main;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import src.Modif.ModifPersonne;
import src.créer.CréerContact;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author M0riz
 */
public class MainPersonne extends javax.swing.JFrame {

    public Vector<Integer> contact_selec = new Vector<Integer>();
    /**
     * Creates new form MainContact
     */
    public MainPersonne() {
        initComponents();
        AllContacts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_contact = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnmodif = new javax.swing.JButton();
        btn_raffraichir = new javax.swing.JButton();
        btnsupp1 = new javax.swing.JButton();
        champ_recherche = new javax.swing.JTextField();
        btnsupp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des contatcs");

        jLabel1.setText("Liste des contact :");

        jButton1.setText("Créer un contact");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panel_contact.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_contactLayout = new javax.swing.GroupLayout(panel_contact);
        panel_contact.setLayout(panel_contactLayout);
        panel_contactLayout.setHorizontalGroup(
            panel_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        panel_contactLayout.setVerticalGroup(
            panel_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jLabel3.setText("Nom :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btn_raffraichir.setText("Rafraichir");
        btn_raffraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raffraichirActionPerformed(evt);
            }
        });

        btnsupp1.setText("Exporter en CSV");
        btnsupp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_raffraichir)
                .addGap(55, 55, 55)
                .addComponent(btnsupp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(192, 192, 192)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panel_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnmodif)
                        .addGap(148, 148, 148)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_raffraichir)
                            .addComponent(btnsupp1))))
                .addGap(18, 18, 18)
                .addComponent(panel_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodif)
                    .addComponent(jButton1)))
        );

        champ_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champ_rechercheActionPerformed(evt);
            }
        });
        champ_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                champ_rechercheKeyReleased(evt);
            }
        });

        btnsupp.setText("Supprimer");
        btnsupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuppActionPerformed(evt);
            }
        });

        jMenu1.setText("Réunions");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Types");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Groupes");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contacts");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(champ_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsupp))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(champ_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(btnsupp))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CréerContact Aff = new CréerContact();
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void champ_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champ_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champ_rechercheActionPerformed

    private void btnsuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuppActionPerformed
        Bdd bdd = new Bdd();
        System.out.println("appui sur supp");
        
        System.out.println(contact_selec);
        
        bdd.SupprimerPersonne(contact_selec);
        
        panel_contact.removeAll();
        AllContacts();
    }//GEN-LAST:event_btnsuppActionPerformed

    private void champ_rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_champ_rechercheKeyReleased
        System.out.println("Appui sur une touche");
        
        panel_contact.removeAll();
        String nom_saisi = champ_recherche.getText();
        Bdd bdd = new Bdd();
        
        ArrayList<Personnes> liste = bdd.recherche_personne(nom_saisi);
        
        System.out.println("taille de la liste : " + liste.size());
        
        Affichage_contacts(liste);
        
    }//GEN-LAST:event_champ_rechercheKeyReleased

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        ModifPersonne Aff = new ModifPersonne();
        Bdd bdd = new Bdd();
        ArrayList<Personnes> liste = bdd.AllContacts(contact_selec.get(0));
        
        int id_pers = liste.get(0).getId();
        String adr_pers = liste.get(0).getMail();
        String prenom_pers = liste.get(0).getPrenom();
        String nom_pers = liste.get(0).getNom();
        
        System.out.println(adr_pers);
        
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
        Aff.Affichage(id_pers,adr_pers,prenom_pers,nom_pers);
    }//GEN-LAST:event_btnmodifActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        MainReunion Aff = new MainReunion();
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        MainType Aff = new MainType();
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        MainGroupe Aff = new MainGroupe();
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void btn_raffraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raffraichirActionPerformed
        AllContacts();
    }//GEN-LAST:event_btn_raffraichirActionPerformed

    private void btnsupp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupp1ActionPerformed
        Bdd bdd = new Bdd();
        ArrayList<Personnes> Listepers;
        if (contact_selec.size() == 1){
            Listepers = bdd.getPersonne(contact_selec.get(0));
            String nom = Listepers.get(0).getNom();
            String prenom = Listepers.get(0).getPrenom();
            String adresse = Listepers.get(0).getMail();
            String base="Name,Given Name,Additional Name,Family Name,"
                        + "Yomi Name,Given Name Yomi,Additional Name Yomi,"
                        + "Family Name Yomi,Name Prefix,Name Suffix,Initials,"
                        + "Nickname,Short Name,Maiden Name,Birthday,Gender,"
                        + "Location,Billing Information,Directory Server,Mileage,"
                        + "Occupation,Hobby,Sensitivity,Priority,Subject,Notes,"
                        + "Language,Photo,Group Membership,E-mail 1 - Type,"
                        + "E-mail 1 - Value,Phone 1 - Type,Phone 1 - Value,"
                        + "Phone 2 - Type,Phone 2 - Value,Relation 1 - Type,"
                        + "Relation 1 - Value";
            String file_content = base + "\n" + nom + "," + prenom + ",," + nom + ",,,,,,,,,,,,,,,,,,,,,,,,,,* Work," + adresse;

            FileWriter myWriter;
            try {
                myWriter = new FileWriter(Main.PathApp+"\\FichierCSV\\"+nom+".csv");
                myWriter.write(file_content);
                myWriter.close(); 
            } catch (IOException ex) {
                Logger.getLogger(MainPersonne.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(contact_selec.size()>1){
            for (int i=0; i<contact_selec.size(); i++){
                Listepers = bdd.getPersonne(contact_selec.get(i));
                System.out.println("contact"+contact_selec.get(0));
                String nom = Listepers.get(0).getNom();
                String prenom = Listepers.get(0).getPrenom();
                String adresse = Listepers.get(0).getMail();
                String base="Name,Given Name,Additional Name,Family Name,"
                        + "Yomi Name,Given Name Yomi,Additional Name Yomi,"
                        + "Family Name Yomi,Name Prefix,Name Suffix,Initials,"
                        + "Nickname,Short Name,Maiden Name,Birthday,Gender,"
                        + "Location,Billing Information,Directory Server,Mileage,"
                        + "Occupation,Hobby,Sensitivity,Priority,Subject,Notes,"
                        + "Language,Photo,Group Membership,E-mail 1 - Type,"
                        + "E-mail 1 - Value,Phone 1 - Type,Phone 1 - Value,"
                        + "Phone 2 - Type,Phone 2 - Value,Relation 1 - Type,"
                        + "Relation 1 - Value";
                String file_content = base + "\n" + nom + "," + prenom + ",," + nom + ",,,,,,,,,,,,,,,,,,,,,,,,,,* Work," + adresse;
                FileWriter myWriter;
                try {
                    myWriter = new FileWriter(Main.PathApp+"\\FichierCSV\\"+nom+".csv");
                    myWriter.write(file_content);
                    myWriter.close(); 
                } catch (IOException ex) {
                    Logger.getLogger(MainPersonne.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnsupp1ActionPerformed
    
    public void AllContacts()
    {
        Bdd bdd= new Bdd();
        panel_contact.removeAll();
        ArrayList<Personnes> liste = bdd.AllContacts(0);
        
        Affichage_contacts(liste);

        
    }
    
    public void selectOptions(Map<Integer, JCheckBox> check_type){
                
                Bdd bdd = new Bdd();
                ArrayList<Personnes> liste = bdd.recherche_personne("");
               
                contact_selec.clear();
                
                /*
		check_type.entrySet().stream().filter(e-> e.getValue().isSelected())
		          .forEach(e-> contact_selec.add(e.getKey()));*/
                
                check_type.entrySet().stream().filter(e-> e.getValue().isSelected())
		          .forEach(e-> contact_selec.add(liste.get(e.getKey()).getId()));
                /*
                check_type.entrySet().stream().filter(e-> !e.getValue().isSelected())
		          .forEach(e-> contact_selec.remove(liste.get(e.getKey()).getId()));*/
                
                System.out.println("taille vecteur après ajout / supp : " + contact_selec.size());
                
                System.out.println(contact_selec);
                
                if (contact_selec.size()<1)
                    btnmodif.setEnabled(false);
                else if (contact_selec.size()==1){
                    btnmodif.setEnabled(true);
                    btnsupp.setEnabled(true);
                }
                else{
                    btnsupp.setEnabled(true);
                    btnmodif.setEnabled(false);
                }
                
    }
    
    public void Affichage_contacts(ArrayList<Personnes>liste){
        
        Map<Integer, JCheckBox> check_type = new HashMap<Integer, JCheckBox>() ;
        int x=50;
        int y=50;
        
        
        for (int i=0;i<liste.size();++i)
        {
            JLabel label1=new JLabel();
            JCheckBox check = new JCheckBox(liste.get(i).getNom() + " " + liste.get(i).getPrenom());
            check_type.put(i, check);
            label1.setBounds(100,y,500,30);
            check.setBounds (30,y,200,30);
            check.addActionListener(new ActionListener(){

            @Override
            public final void actionPerformed(ActionEvent e) {
                selectOptions(check_type);
            }
  
                
            
        });
            

            panel_contact.add(label1);
            panel_contact.add(check);

            x+=30;
            y+=30;
        }
        
        
        panel_contact.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPersonne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_raffraichir;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsupp;
    private javax.swing.JButton btnsupp1;
    private javax.swing.JTextField champ_recherche;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_contact;
    // End of variables declaration//GEN-END:variables
}
