package src.créer;

import src.Rechercher.RecherchePersonne;
import src.main.Bdd;

/**
 * @author Morgan
 */
public class CréerType extends javax.swing.JFrame {

    /**
     * Creates new form CréerType
     */
    public CréerType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondReunion = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        BEnregister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btn_ajout_pers = new javax.swing.JButton();
        add_groupe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Créer un type de réunion");

        BAnnuler.setText("Annuler");

        BEnregister.setText("Enregistrer");
        BEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnregisterActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom du nouveau type : ");

        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        btn_ajout_pers.setText("Ajouter/Dissocier des personnes");
        btn_ajout_pers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajout_persActionPerformed(evt);
            }
        });

        add_groupe.setText("Associer/Dissocier des groupes");
        add_groupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_groupeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondReunionLayout = new javax.swing.GroupLayout(FondReunion);
        FondReunion.setLayout(FondReunionLayout);
        FondReunionLayout.setHorizontalGroup(
            FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondReunionLayout.createSequentialGroup()
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(FondReunionLayout.createSequentialGroup()
                                    .addComponent(BAnnuler)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BEnregister))
                                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ajout_pers)
                            .addComponent(add_groupe))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        FondReunionLayout.setVerticalGroup(
            FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondReunionLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_ajout_pers)
                .addGap(39, 39, 39)
                .addComponent(add_groupe)
                .addGap(45, 45, 45)
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAnnuler)
                    .addComponent(BEnregister))
                .addGap(171, 171, 171))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondReunion, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnregisterActionPerformed
       Bdd bdd = new Bdd();
       
       String nom_type = Nom.getText();
       
       bdd.ajoutType(nom_type);
       
       bdd.add_pers_newtype();
       
       bdd.add_groupe_newtype();
       
       
       this.dispose();
    }//GEN-LAST:event_BEnregisterActionPerformed

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomActionPerformed

    private void btn_ajout_persActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajout_persActionPerformed
        RecherchePersonne Aff = new RecherchePersonne(-4,0);
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
    }//GEN-LAST:event_btn_ajout_persActionPerformed

    private void add_groupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_groupeActionPerformed
        RecherchePersonne Aff = new RecherchePersonne(-3,0);
        Aff.setLocationRelativeTo(null);
        Aff.setVisible(true);
    }//GEN-LAST:event_add_groupeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CréerType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CréerType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CréerType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CréerType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CréerType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BEnregister;
    private javax.swing.JPanel FondReunion;
    private javax.swing.JTextField Nom;
    private javax.swing.JButton add_groupe;
    private javax.swing.JButton btn_ajout_pers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
