package src.créer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.time.format.DateTimeFormatter;  
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import src.main.Types;
import src.main.Bdd;
import src.Rechercher.RecherchePersonne;
/**
 *
 * @author M0riz
 */
public class CréerRéunion extends javax.swing.JFrame{
    
    
    Vector<Integer> liste_pers = new Vector<Integer>();
    /**
     * Creates new form Réunion
     */
    public CréerRéunion() {
        initComponents();
        Types_init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondReunion = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        Lieu = new javax.swing.JTextField();
        Date = new javax.swing.JFormattedTextField();
        Heure = new javax.swing.JFormattedTextField();
        Periodicite = new javax.swing.JCheckBox();
        nbjours = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_ajoutergroupe = new javax.swing.JButton();
        btn_ajouterpers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Créer une réunion");

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });

        btn_save.setText("Enregistrer");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom de la réunion : ");

        jLabel3.setText("Type de la réunion : ");

        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Heure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeureActionPerformed(evt);
            }
        });

        Periodicite.setText("Valider périodicité");

        nbjours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbjoursActionPerformed(evt);
            }
        });

        jLabel4.setText("Lieu : ");

        jLabel2.setText("Date :");

        jLabel5.setText("Heure :");

        jLabel6.setText("Périodicité :");

        jLabel7.setText("Semaines");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        btn_ajoutergroupe.setText("Ajouter un groupe");
        btn_ajoutergroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajoutergroupeActionPerformed(evt);
            }
        });

        btn_ajouterpers.setText("Ajouter personne");
        btn_ajouterpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterpersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondReunionLayout = new javax.swing.GroupLayout(FondReunion);
        FondReunion.setLayout(FondReunionLayout);
        FondReunionLayout.setHorizontalGroup(
            FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondReunionLayout.createSequentialGroup()
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(BAnnuler)
                        .addGap(131, 131, 131)
                        .addComponent(btn_save))
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(FondReunionLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Heure, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FondReunionLayout.createSequentialGroup()
                                .addComponent(Periodicite)
                                .addGap(18, 18, 18)
                                .addComponent(nbjours, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ajoutergroupe)
                            .addComponent(btn_ajouterpers))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondReunionLayout.setVerticalGroup(
            FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondReunionLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Periodicite)
                    .addComponent(nbjours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ajouterpers)
                .addGap(18, 18, 18)
                .addComponent(btn_ajoutergroupe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAnnuler)
                    .addComponent(btn_save))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void HeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeureActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
     
        String r_nom=Nom.getText();
        
        if(r_nom.equals("")){
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"le nom de la réunion ne peut pas être vide ! ");
        }
        else{
            String r_lieu=Lieu.getText();
        
            String r_date=Date.getText();

            String r_heure=Heure.getText();

            String r_typereu = (String)Type.getSelectedItem();
            
            DateTimeFormatter dtf;
            dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDate current_date = LocalDate.now();
            System.out.println("date ajd " + current_date);

            int r_perio=0;
            int r_duree=0;
            if(Periodicite.isSelected())
            {
                r_perio=1;
                r_duree=0; //Remplacer par nombre de semaines selectionnées 
            }
            else {
                r_perio=0;
                r_duree=0;
            }


            if(!r_date.equals("")){ 

                    //appel de la fonction
                    LocalDate d_date_reu = LocalDate.parse(r_date, dtf);
                    long daysBetween = 0;
                    daysBetween = ChronoUnit.DAYS.between(current_date, d_date_reu);

                    if(daysBetween<21){
                            JFrame frame = new JFrame();
                            JOptionPane.showMessageDialog(frame,"Cette réunion ne peut pas être ajouté car la date est inférieure à 21 jours.");
                    }
                    else{

                        if(!r_heure.equals("")){//on vérifie qu'on a pas une réunion 1 heure avant 
                            System.out.println("on vérifie l'heure");
                            Bdd bdd = new Bdd();
                            boolean verif_heure = bdd.verif_heure(r_date,r_heure);

                            if(verif_heure==true){
                                 ajout_bdd(r_nom,r_typereu,r_date,r_heure,r_lieu,r_perio,r_duree);
                                 System.out.println("taille de la liste :" + liste_pers.size());
                            }

                            else{
                                JFrame frame = new JFrame();
                                JOptionPane.showMessageDialog(frame,"Vous avez déjà une réunion programmé à moins d'une heure.");
                            }
                        }
                        else{
                            ajout_bdd(r_nom,r_typereu,r_date,r_heure,r_lieu,r_perio,r_duree);
                            
                            //ajout des personnes et du groupe

                        }



                    }

                }//ferme le grand if
                else{
                    ajout_bdd(r_nom, r_typereu, r_date, r_heure, r_lieu, r_perio, r_duree);
                    
                    //ajout des personnes et du groupe
                    

                }

        
        this.dispose();
        }
        
                
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void nbjoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbjoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbjoursActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void btn_ajouterpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterpersActionPerformed
        RecherchePersonne aff = new RecherchePersonne(-1,0);
        aff.setLocationRelativeTo(null);
        aff.setVisible(true);
        
        
    }//GEN-LAST:event_btn_ajouterpersActionPerformed

    private void btn_ajoutergroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajoutergroupeActionPerformed
        RecherchePersonne aff = new RecherchePersonne(-2,0);
        aff.setLocationRelativeTo(null);
        aff.setVisible(true);
    }//GEN-LAST:event_btn_ajoutergroupeActionPerformed
    
    
    public void ajout_bdd(String r_nom,String r_typereu,String r_date,String r_heure,String r_lieu,int r_perio,int r_duree){
        Bdd bdd = new Bdd();
        ArrayList<Types> liste = bdd.allTypes();
                   
        int id_type=0;
        for (int i=0;i<liste.size();i++){
            if (r_typereu.equals(liste.get(i).getType())){
               id_type = liste.get(i).getId();
               break;
            }
                           //get l'id de la réunion 
        }
        bdd.ajouterReunion(r_nom,r_date,r_heure, r_lieu, r_perio, r_duree, id_type);
        
        bdd.add_personne_newreu(); //prend la liste temp personne et l'ajoute à la réu
        
        bdd.add_groupe_newreu(); //prend la liste temp du groupe et l'ajoute à la réu
        

        
        
    }
    
    
    public void Types_init(){
        Bdd bdd = new Bdd();
        
         ArrayList<Types> liste = bdd.allTypes();
        if (liste.isEmpty() == false){
        for (int i=0;i<liste.size();++i)
        {
            Type.addItem(liste.get(i).getType());
        }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CréerRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CréerRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CréerRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CréerRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CréerRéunion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JFormattedTextField Date;
    private javax.swing.JPanel FondReunion;
    private javax.swing.JFormattedTextField Heure;
    private javax.swing.JTextField Lieu;
    private javax.swing.JTextField Nom;
    private javax.swing.JCheckBox Periodicite;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JButton btn_ajoutergroupe;
    private javax.swing.JButton btn_ajouterpers;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nbjours;
    // End of variables declaration//GEN-END:variables
}
