package src.Modif;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import src.main.Reunions;
import src.main.Bdd;
import src.Rechercher.RecherchePersonne;
import src.main.Types;
/**
 *
 * @author louis
 */
public class ModifRéunion extends javax.swing.JFrame {

    /**
     * Creates new form ModifRéunion
     */
    ArrayList<Types> liste_types = new ArrayList<Types>();
    
    private int id_reu;
    public ModifRéunion() {
        initComponents();
        initList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondReunion = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        BEnregister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        Lieu = new javax.swing.JTextField();
        Date = new javax.swing.JFormattedTextField();
        Heure = new javax.swing.JFormattedTextField();
        Periodicite = new javax.swing.JCheckBox();
        nbjours = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        btn_ajoutpers = new javax.swing.JButton();
        btn_ajoutgrp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });

        BEnregister.setText("Enregistrer");
        BEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnregisterActionPerformed(evt);
            }
        });

        jLabel3.setText("Type de la réunion : ");

        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Heure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeureActionPerformed(evt);
            }
        });

        Periodicite.setText("Valider périodicité");

        nbjours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbjoursActionPerformed(evt);
            }
        });

        jLabel4.setText("Lieu : ");

        jLabel2.setText("Date :");

        jLabel5.setText("Heure :");

        jLabel6.setText("Périodicité :");

        jLabel7.setText("Semaines");

        jLabel1.setText("Nom de la réunion : ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Nom))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_ajoutpers.setText("Ajouter une personne");
        btn_ajoutpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajoutpersActionPerformed(evt);
            }
        });

        btn_ajoutgrp.setText("Ajouter un groupe");
        btn_ajoutgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajoutgrpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondReunionLayout = new javax.swing.GroupLayout(FondReunion);
        FondReunion.setLayout(FondReunionLayout);
        FondReunionLayout.setHorizontalGroup(
            FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondReunionLayout.createSequentialGroup()
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(Heure)))
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(BAnnuler)
                        .addGap(149, 149, 149)
                        .addComponent(BEnregister))
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(FondReunionLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_ajoutpers)
                            .addGroup(FondReunionLayout.createSequentialGroup()
                                .addComponent(Periodicite)
                                .addGap(37, 37, 37)
                                .addComponent(nbjours, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(FondReunionLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btn_ajoutgrp)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        FondReunionLayout.setVerticalGroup(
            FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondReunionLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Periodicite)
                    .addComponent(nbjours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ajoutpers)
                .addGap(18, 18, 18)
                .addComponent(btn_ajoutgrp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(FondReunionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAnnuler)
                    .addComponent(BEnregister))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void HeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeureActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void BEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnregisterActionPerformed

        Bdd bdd = new Bdd();

        String r_nom=Nom.getText();
        String r_lieu=Lieu.getText();

        String r_date=Date.getText();

        String r_heure=Heure.getText();

        int r_typereu = Type.getSelectedIndex()+1;
        
        
        System.out.println("type choisi sur bouton ajout" + r_typereu);

        int r_perio = 0;
        int r_duree = 0;

        if(Periodicite.isSelected())
        {
            r_perio=1;
            r_duree=0; //Remplacer par nombre de semaines selectionnées
        }
        else {
            r_perio=0;
            r_duree=0;
        }

        bdd.Modifier_reunion(id_reu,r_typereu,r_nom,r_lieu,r_date,r_heure,r_perio,r_duree);
        
        this.dispose();
    }//GEN-LAST:event_BEnregisterActionPerformed
    

    public void Affichage(int id_reu,String nom_reu,int type_reu,String lieu_reu,String date_reu,String heure_reu,boolean perio_reu,int semaines_reu)
    {
        setIdReu(id_reu); //pour savoir quelle réu pour pouvoir la modifier 
        
        Nom.setText(nom_reu);
        Lieu.setText(lieu_reu);
        Date.setText(date_reu);
        Heure.setText(heure_reu);
        System.out.println("type chosii a l'init " + type_reu);
        Type.getModel().setSelectedItem(type_reu); //Problème au niveau de la réu selectionné 
        Periodicite.setSelected(perio_reu);
        nbjours.setText(Integer.toString(semaines_reu));
        
        
    }
    private void nbjoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbjoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbjoursActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void btn_ajoutpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajoutpersActionPerformed
        RecherchePersonne aff = new RecherchePersonne(1,id_reu);
        aff.setLocationRelativeTo(null);
        aff.setVisible(true);
        aff.setId(id_reu);
    }//GEN-LAST:event_btn_ajoutpersActionPerformed

    private void btn_ajoutgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajoutgrpActionPerformed
        RecherchePersonne aff = new RecherchePersonne(6,id_reu);
        aff.setLocationRelativeTo(null);
        aff.setVisible(true);
        aff.setId(id_reu);
    }//GEN-LAST:event_btn_ajoutgrpActionPerformed
    
    public int getIdReu(){
        return id_reu;
    }
    
    public void setIdReu(int id_reu){
        this.id_reu = id_reu;
    }
    
    public void initList(){
        Bdd bdd = new Bdd();
        liste_types = bdd.allTypes();
        
        if(liste_types.size()==1){
            Type.addItem(liste_types.get(0).getType());
        }
        
        else if(liste_types.size()>1){
            for(int i=0;i<liste_types.size();++i){
                Type.addItem(liste_types.get(i).getType());
            }
        }
       
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifRéunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifRéunion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BEnregister;
    private javax.swing.JFormattedTextField Date;
    private javax.swing.JPanel FondReunion;
    private javax.swing.JFormattedTextField Heure;
    private javax.swing.JTextField Lieu;
    private javax.swing.JTextField Nom;
    private javax.swing.JCheckBox Periodicite;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JButton btn_ajoutgrp;
    private javax.swing.JButton btn_ajoutpers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nbjours;
    // End of variables declaration//GEN-END:variables
}
