package fichiersreu;

import com.itextpdf.text.DocumentException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileNotFoundException;
import java.io.FileReader;
import src.main.*;

/**
 * @author louis
 */

public class Ordredujour extends javax.swing.JFrame {

    /**
     * Creates new form Ordredujour
     */
    private String nom_reu;
    private int id;
    String DossierODJ = "\\SauvegardeOrdreDuJour\\OrdreDuJour_";
    
    public Ordredujour(String nom_reu,int id) {
        this.nom_reu=nom_reu;
        this.id = id;
        initComponents();
        Check_file();
    }

    private Ordredujour() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_odj = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        zone_texte = new javax.swing.JTextArea();
        btn_annuler = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordre du jour");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        label_odj.setText("Ordre du jour");

        zone_texte.setColumns(20);
        zone_texte.setRows(5);
        jScrollPane1.setViewportView(zone_texte);

        btn_annuler.setText("Annuler");
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        btn_save.setText("Sauvegarder");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(label_odj)
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_odj)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_annuler)
                    .addComponent(btn_save))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String ordre = zone_texte.getText();
        File ODJExiste = new File(Main.PathApp+DossierODJ+nom_reu);
        try {
            Bdd bdd = new Bdd();
            String Date_Reu = bdd.getDateReu(id);
            String Heure_Reu = bdd.getHeureReu(id);
            String Lieu_Reu = bdd.getLieuReu(id);
            
            if(ODJExiste.createNewFile()){
                System.out.println("Le fichier est créé");
                ListePdf.PageConvoc(nom_reu,ordre,
                        Date_Reu,Heure_Reu,Lieu_Reu);
                FileWriter myWriter = new FileWriter(Main.PathApp+DossierODJ+nom_reu);
                myWriter.write(ordre);
                myWriter.close();
            }
            else {
                System.out.println("Récriture du fichier");
                ListePdf.PageConvoc(nom_reu,ordre,
                        Date_Reu,Heure_Reu,Lieu_Reu);
                FileWriter myWriter = new FileWriter(Main.PathApp+DossierODJ+nom_reu);
                myWriter.write(ordre);
                myWriter.close();
            }
        } 
        catch (IOException | DocumentException ex) {
            Logger.getLogger(Ordredujour.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordredujour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordredujour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordredujour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordredujour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordredujour().setVisible(true);
            }
        });
    }
    
    public void setNom(String nom_reu){
        this.nom_reu=nom_reu;
    }
    
    public String getNom(){
        return nom_reu;
    }
    
    public void Check_file(){
        
        File fichier = new File(Main.PathApp+DossierODJ+nom_reu);
        String st = "";
        
        if(fichier.exists()){
            System.out.println("l'odj existe déjà");
            try {
                FileReader fr = new FileReader(Main.PathApp+DossierODJ+nom_reu); 
                int character;
                while ((character = fr.read()) != -1) {
                    System.out.print((char) character);
                    st += (char)character;
                }
                zone_texte.setText(st);
                fr.close();
            } 
            catch (FileNotFoundException ex) {
                Logger.getLogger(Ordredujour.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (IOException ex) {
                Logger.getLogger(Ordredujour.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_save;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_odj;
    private javax.swing.JTextArea zone_texte;
    // End of variables declaration//GEN-END:variables
}
